---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-ecr-login
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Cloud, Image Build
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: aws, ecr
    tekton.dev/displayName: "Amazon ECR Login"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task retrieves an `authentication token` using the GetAuthorizationToken API
    that you can use to authenticate to an `Amazon ECR registry`

    You can pass the authorization token to the login command of the container
    client of your preference, such as the Docker CLI. After you have
    authenticated to an Amazon ECR registry with this authentication token, you
    can use the client to push and pull images from that registry as long as your
    IAM principal has access to do so until the token expires.

  workspaces:
    - name: secrets
      mountPath: /root/.aws
  params:
    - name: region
      type: string
      default: "eu-central-1"

  steps:
    - name: get-login-password
      image: docker.io/amazon/aws-cli:latest
      script: |
        aws ecr get-login-password --region $(params.region) > $(results.password.path)
  results:
    - name: password
      description: The password to authenticate to ecr registry.