---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bash
spec:
  workspaces:
    - name: source
  params: 
    - name: BASE_IMAGE
      default: alpine:latest
    - name: BASH_SCRIPT
      description: The bash script to run.
      type: string
  steps:
    - name: bash
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)/argocd
      script: |
        #!/usr/bin/env sh
        set -eu

        eval '$(params.BASH_SCRIPT)'

        EXIT_CODE="$?"
        if [ "$EXIT_CODE" != 0 ]
        then
          exit $EXIT_CODE
        fi