apiVersion: v1
kind: Secret
metadata:
  name: docker-config
stringData:
  config.json: |-
    { "credsStore": "ecr-login", "credHelpers":{"<AWS_ACC_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com":"ecr-login"}} }